### ISSUE TITLE
tab should auto complete file names

### ISSUE THREAD

**Issue by ericllazarus** [myTerminal/super-emacs#6] opened 2019-07-07 15:37 UTC
I'm so used to typing find file (^x^f) and using tab to complete director and file names. Any way we can turn that back on w/o removing helm? 

https://emacs.stackexchange.com/questions/33727/how-does-spacemacs-allow-tab-completion-in-helm

THANKS!

**Comment by myTerminal** [comment] 2019-11-01 06:22
I replaced helm with ivy (along with counsel and swiper), which are lighter, faster and opinionatedly superior. ivy uses tab completion and hence it should solve the problem of non-standard input.

@ericllazarus, kindly let me know how it feels now.

**Comment by myTerminal** [comment] 2019-11-02 03:56
I'm closing this issue as the problem is not there anymore. Feel free to re-open in case of any issues.

**Closed as completed by myTerminal** 2019-11-02 03:56 UTC
Labels: enhancement
